### PR TITLE
Add ShowDeadNpcNames option in Reloaded.cfg

### PR DESCRIPTION
**Pull request by LinuxFO**
I like feature that NPC names can be shown over head https://github.com/Sasabmeg/FOnline-BraveNewWorld/issues/116 but I want to upgrade it by introducing parameter `ShowDeadNpcNames`.  We could customize displaying of alive/dead NPC names. I dont like displaying names for dead NPCs so I can change parameter.

I also added small code style format and changes (however not all script). I think more updates would be good but I guess not right now.

### CODE REVIEW

**Comment by Sasabmeg** [comment]
First.

The change seems reasonable, for this very same reason I had to change the color of the dead NPC to something that doesn't stand out, but guess disabling dead NPC names is even better.

Second.

Please do not reformat the code when doing changes, because it is harder to see where the actual differences are.
If reformat is required, it would need to be pushed in a different commit, that does change nothing but reformat the code, however this is not required, nor wanted atm.

I can post your changes manually if you have issues setting up IDE like that, but for next time do not reformat in same change list where you also make code changes.

Third.

Even if reformatted, I wouldn't like to see function names with every parameter in new line like this:
image

So for now, if you introduce changes, you can use your own format, but do not reformat other code.
There is some ugly shit there, I know, but for now it stays as it is.

**Comment by LinuxFO** [comment]
Ok, thanks. I reverted previous changes and created new commit.

Generally speaking displaying colored dead NPC names is not bad idea however I find it messy when there is a lot critters. It is reason I added second parameter, so it is possible to enable or disable dead NPC names.

>  if you have issues setting up IDE like that

Do you have code formatter/prettier to share? I use VS Code but I don't know if it is supported (probably not right now).

> There is some ugly shit there, I know, but for now it stays as it is.

Yes and lack of codebase knowledge is another difficulty at least for me. But let's see what can be done to get better features.

**Comment by LinuxFO** [comment]
Can it be merged?

**Comment by LinuxFO** [comment]
Still not merged?

**Pull request closed without merging**
